name: Build Padavan Firmware (Manual Toolchain)

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Đổi thành master vì repo của bạn đang dùng nhánh chính là master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Mã nguồn từ Repo hiện tại
      uses: actions/checkout@v4

    - name: Cài đặt Dependencies
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin \
            libctf-nobfd0 libcunit1-dev libhdf5-dev libopenblas-dev -y

    - name: Tự Compile Toolchain (Manual)
      run: |
        cd toolchain-mipsel
        ./clean_toolchain
        ./build_toolchain

    - name: Compile Firmware
      run: |
        cd trunk
        sudo ./clear_tree
        
        # 1. Chép đè file cấu hình tính năng tối ưu vào template và tạo .config gốc
        if [ -f "$GITHUB_WORKSPACE/NEWIFI3.config" ]; then
          cp -f $GITHUB_WORKSPACE/NEWIFI3.config configs/templates/NEWIFI3.config
          cp -f configs/templates/NEWIFI3.config .config
        fi
        
        # 2. Chép đè cấu hình Kernel tối ưu vào đúng thư mục board của NEWIFI3
        if [ -f "$GITHUB_WORKSPACE/kernel-3.4.x.config" ]; then
          cp -f $GITHUB_WORKSPACE/kernel-3.4.x.config configs/boards/NEWIFI3/kernel-3.4.x.config
        fi
        
        # Tiến hành build
        fakeroot ./build_firmware_modify NEWIFI3

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: Padavan_NEWIFI3_Optimized
        path: trunk/images/*.trx
        
